/* DATA for Async in Depth. Edit this file; the engine never needs rebuilding.

   Scenario: { id, title, intro, code[], tokens{}, bars?, evidence[], steps[] }
   code:     [{ id, title, lines[] }]                 line numbers are 1-based per card
   tokens:   { id: { label, sub?, kind, from } }      kind: micro | task | job | promise
   Slots:    stack:i  heap:i  micro:i  macro:i  host:i  code:<card>:<line>
   Step:     { cam, lod, note, line?, parked?, stack?, loop?, out?, t?, tokens?, bars?, predict?, ev? }
             cam:  far | left | work | queues | loop | host | right
             lod:  1 function, 2 promise, 3 engine
             loop: idle | run | micro | blocked
             tokens: { id: "slot" } or { id: { at, label?, sub?, state?, p? } }
             predict: { q, options[], answer, why }
   Evidence: { how: "run" | "known", sure: "high" | "medium" | "low", claim, proof? }
   Longer text per step lives in window.MORE at the end of this file and is merged in as step.more.
*/
window.SCENARIOS = [

  {
    id: "anatomy",
    title: "Anatomy",
    intro: "What each part is, and who may put what where.",
    code: [
      { id: "fetch", title: "fetchUser", lines: [
        "const fetchUser = () =>",
        "  new Promise(res =>",
        "    setTimeout(() => res(\"Ada\"), 300));" ] },
      { id: "main", title: "script", lines: [
        "async function load() {",
        "  console.log(\"A\");",
        "  const user = await fetchUser();",
        "  console.log(\"C\", user);",
        "}",
        "load();",
        "console.log(\"B\");" ] }
    ],
    tokens: {
      pr:   { label: "a promise", sub: "pending, then settled", kind: "promise", from: "heap:0" },
      cont: { label: "a parked continuation", sub: "the rest of a function", kind: "micro", from: "heap:1" },
      tk:   { label: "a task", sub: "timer, click, socket", kind: "task", from: "host:0" },
      job:  { label: "work in flight", sub: "the host is doing it", kind: "job", from: "host:0" }
    },
    evidence: [
      { how: "known", sure: "high", claim: "The components and the rules for who may enqueue where follow the HTML event loop and ECMAScript job queue model. Not read this session." },
      { how: "known", sure: "medium", claim: "Spec names in the 'In the spec' sections are quoted from memory of the ECMAScript and HTML specifications; names change between editions and were not checked this session." }
    ],
    steps: [
      { cam: "far", lod: 1, loop: "idle", stack: [],
        note: "Three sheets. Front: the code you wrote. Middle: the JavaScript runtime, which runs it. Back: the host, which is not JavaScript at all. Every later scenario is drawn on these three sheets." },
      { cam: "left", lod: 1, loop: "run", stack: ["script", "load()"], line: { main: 2 }, out: ["A"],
        note: "Your code. Lines run from the top, one at a time, and the console shows what printed. The highlighted line is the one running right now; a line from it points to the frame that runs it." },
      { cam: "stack", lod: 2, loop: "run", stack: ["script", "load()", "fetchUser()"], line: { fetch: 3 }, out: ["A"],
        note: "The call stack. Every function that has been called and has not returned has a frame here. Only the top frame runs. There is one stack, so one thing runs at a time, and whatever is on it runs until the stack is empty." },
      { cam: "heap", lod: 2, loop: "run", stack: ["script"], line: { main: 7 }, parked: { main: [4, 5] }, out: ["A"],
        tokens: { pr: "heap:0", cont: "heap:1" },
        note: "The heap. Everything that must outlive a frame lives here: objects, closures, promises, and the parked rest of an async function. A promise is a record with a state and a list of reactions; it does not compute anything." },
      { cam: "micro", lod: 2, loop: "idle", stack: [], out: ["A", "B"],
        tokens: { pr: { at: "heap:0", sub: "fulfilled", state: "fulfilled" }, cont: "micro:0" },
        note: "The microtask queue. Only promises put things here (and queueMicrotask). When a promise settles, each of its reactions is appended as a microtask. The loop empties this queue completely before it takes another task." },
      { cam: "macro", lod: 2, loop: "idle", stack: [], out: ["A", "B"],
        tokens: { tk: "macro:0" },
        note: "The task queue. Only the host puts things here: an expired timer, a finished request, a click. The loop takes one task per turn. This is the host's single door into JavaScript." },
      { cam: "loop", lod: 2, loop: "micro", stack: [], out: ["A", "B"],
        tokens: { tk: "macro:0", cont: "micro:0" },
        note: "The event loop. Three states, forever: run one task until the stack is empty; then run every microtask; then wait for the next task. It is the only thing that moves work from a queue onto the stack." },
      { cam: "host", lod: 3, loop: "idle", stack: [], out: ["A", "B"], t: 150,
        tokens: { job: { at: "host:0", p: 0.5 } },
        note: "The host: the browser or Node, with the operating system behind it. Timers count here, sockets wait here, files are read here, on threads that are not JavaScript. When something finishes, the host queues a task and nothing more." },
      { cam: "far", lod: 2, loop: "idle", stack: [], out: ["A", "B"],
        tokens: { pr: { at: "heap:0", sub: "fulfilled", state: "fulfilled" }, cont: "micro:0", tk: "macro:0", job: { at: "host:0", p: 0.5 } },
        note: "Who puts what where. A call pushes a frame. A settling promise queues a microtask. The host queues a task. The loop moves queued work onto the stack. Nothing else moves anything; the rest of the course is these four rules in combination." }
    ]
  },
  {
    id: "roundtrip",
    title: "One await",
    intro: "A single await, followed through every layer.",
    code: [
      { id: "fetch", title: "fetchUser", lines: [
        "const fetchUser = () =>",
        "  new Promise(res =>",
        "    setTimeout(() => res(\"Ada\"), 300));" ] },
      { id: "main", title: "script", lines: [
        "async function load() {",
        "  console.log(\"A\");",
        "  const user = await fetchUser();",
        "  console.log(\"C\", user);",
        "}",
        "load();",
        "console.log(\"B\");" ] }
    ],
    tokens: {
      q:    { label: "promise of load()", sub: "pending", kind: "promise", from: "stack:1" },
      p:    { label: "promise p", sub: "pending", kind: "promise", from: "stack:2" },
      job:  { label: "timer 300 ms", sub: "holds () => res(\"Ada\")", kind: "job", from: "stack:2" },
      cb:   { label: "timer callback", sub: "() => res(\"Ada\")", kind: "task", from: "host:0" },
      cont: { label: "rest of load()", sub: "lines 4 and 5", kind: "micro", from: "stack:1" }
    },
    evidence: [
      { how: "known", sure: "medium", claim: "Spec names in the 'In the spec' sections are quoted from memory of the ECMAScript and HTML specifications; names change between editions and were not checked this session." },
      { how: "run", sure: "high", claim: "Output order is A, B, C Ada, and load() resumes about 300 ms after the call.",
        proof: "node v22.22.0, this session:\nA\nB\nC Ada\n[resumed after ~300 ms]" },
      { how: "known", sure: "high", claim: "The mechanism drawn here (promise reaction jobs, task queue, microtask checkpoint) is the standard model from the ECMAScript and HTML specifications. It was not read this session." }
    ],
    steps: [
      { cam: "far", lod: 1, loop: "idle", stack: [],
        note: "Three sheets, front to back: your code, the JavaScript runtime with its single call stack, and the host (browser or Node) that owns timers and the network." },
      { cam: "left", lod: 1, loop: "run", stack: ["script"], line: { main: 6 },
        note: "The script runs as the first task. Line 6 calls load()." },
      { cam: "left", lod: 1, loop: "run", stack: ["script", "load()"], line: { main: 2 }, out: ["A"],
        tokens: { q: "heap:0" },
        note: "load() gets a frame on the call stack and runs like any other function. The call also creates load()'s own promise, pending until load() has finished. It prints A." },
      { cam: "far", lod: 1, loop: "run", stack: ["script", "load()", "fetchUser()"], line: { fetch: 3 }, out: ["A"], t: 0,
        tokens: { q: "heap:0", p: "heap:1", job: { at: "host:0", p: 0 } },
        note: "fetchUser() creates a promise p, still pending, and hands the host a 300 ms timer. That work has left the JavaScript thread." },
      { cam: "left", lod: 1, loop: "run", stack: ["script", "load()"], line: { main: 3 }, out: ["A"], t: 0,
        tokens: { q: "heap:0", p: "heap:1", job: { at: "host:0", p: 0.03 } },
        predict: { q: "load() reaches await with a promise that is still pending. What runs next?",
          options: ["Line 4, once the 300 ms have passed", "Line 7, console.log(\"B\")", "Nothing. The thread waits for the timer"],
          answer: 1, why: "await never waits on the stack. It hands control back to the caller." } },
      { cam: "work", lod: 2, loop: "run", stack: ["script"], line: { main: 3 }, parked: { main: [4, 5] }, out: ["A"], t: 0,
        tokens: { q: "heap:0", p: "heap:1", cont: "heap:2", job: { at: "host:0", p: 0.05 } },
        note: "Closer: await unfolds. The rest of load(), lines 4 and 5, is lifted off the stack and registered on p as its reaction. load() returns its own promise, still pending, to its caller, which ignores it. The frame is gone, the function is not." },
      { cam: "left", lod: 1, loop: "run", stack: ["script"], line: { main: 7 }, parked: { main: [4, 5] }, out: ["A", "B"], t: 0,
        tokens: { q: "heap:0", p: "heap:1", cont: "heap:2", job: { at: "host:0", p: 0.1 } },
        note: "Back in the script, line 7 prints B. So far: A, then B, with load() only half done." },
      { cam: "host", lod: 3, loop: "idle", stack: [], parked: { main: [4, 5] }, out: ["A", "B"], t: 180,
        tokens: { q: "heap:0", p: "heap:1", cont: "heap:2", job: { at: "host:0", p: 0.6 } },
        note: "Closest level. The script has ended and the stack is empty: the JavaScript thread is free. The timer counts down inside the host, on the host's own machinery." ,
        ev: [{ how: "known", sure: "high", claim: "Timers and network I/O are handled by the host (browser internals, libuv in Node), not by the thread that runs JavaScript." }] },
      { cam: "host", lod: 3, loop: "idle", stack: [], parked: { main: [4, 5] }, out: ["A", "B"], t: 300,
        tokens: { q: "heap:0", p: "heap:1", cont: "heap:2", cb: "macro:0" },
        note: "300 ms. The host cannot call into JavaScript on its own. It puts the timer's callback in the task queue and leaves it there." },
      { cam: "queues", lod: 3, loop: "run", stack: [], line: { fetch: 3 }, parked: { main: [4, 5] }, out: ["A", "B"], t: 300,
        tokens: { q: "heap:0", p: { at: "heap:1", sub: "fulfilled: \"Ada\"", state: "fulfilled" }, cont: "micro:0", cb: "stack:0" },
        note: "The event loop takes that task and runs it. It calls res(\"Ada\"): p is fulfilled, and p's reaction, the parked rest of load(), moves into the microtask queue." },
      { cam: "work", lod: 2, loop: "micro", stack: [], line: { main: 4 }, out: ["A", "B", "C Ada"], t: 300,
        tokens: { q: { at: "heap:0", sub: "fulfilled: undefined", state: "fulfilled" }, p: { at: "heap:1", sub: "fulfilled: \"Ada\"", state: "fulfilled" }, cont: { at: "stack:0", label: "load() resumed", sub: "from line 4" } },
        note: "The task is over and the stack is empty, so the loop drains its microtasks. The continuation goes back on the stack and load() carries on at line 4 with user = \"Ada\", prints C Ada and ends: its own promise is fulfilled, with undefined." },
      { cam: "far", lod: 1, loop: "idle", stack: [], out: ["A", "B", "C Ada"], t: 300,
        note: "From far away, load() paused at line 3 and resumed. Underneath sat a promise, a callback in the task queue and a reaction in the microtask queue. await is that round trip, folded up." }
    ]
  },

  {
    id: "overlap",
    title: "Sequential or concurrent",
    intro: "Two requests of 300 ms each, asked for in two ways.",
    code: [
      { id: "fn", title: "script  ·  each get() takes 300 ms", lines: [
        "async function inTurn() {",
        "  const a = await get(\"a\");",
        "  const b = await get(\"b\");",
        "  return [a, b];",
        "}",
        "async function together() {",
        "  const pa = get(\"a\"), pb = get(\"b\");",
        "  return [await pa, await pb];",
        "}",
        "let t = Date.now();",
        "console.log(await inTurn(), Date.now() - t);",
        "t = Date.now();",
        "console.log(await together(), Date.now() - t);" ] }
    ],
    tokens: {
      ja:   { label: "request a", sub: "300 ms in the host", kind: "job", from: "stack:1" },
      jb:   { label: "request b", sub: "300 ms in the host", kind: "job", from: "stack:1" },
      ca:   { label: "a arrived", sub: "resolves promise a", kind: "task", from: "host:0" },
      cb:   { label: "b arrived", sub: "resolves promise b", kind: "task", from: "host:1" },
      pa:   { label: "promise pa", sub: "pending", kind: "promise", from: "stack:1" },
      pb:   { label: "promise pb", sub: "pending", kind: "promise", from: "stack:1" },
      cont: { label: "rest of function", sub: "parked at await", kind: "micro", from: "stack:1" }
    },
    bars: { max: 600, rows: [
      { id: "sa", label: "inTurn · a" }, { id: "sb", label: "inTurn · b" },
      { id: "ca", label: "together · a" }, { id: "cb", label: "together · b" } ] },
    evidence: [
      { how: "known", sure: "medium", claim: "Spec names in the 'In the spec' sections are quoted from memory of the ECMAScript and HTML specifications; names change between editions and were not checked this session." },
      { how: "run", sure: "high", claim: "With 300 ms per request, inTurn() takes about 600 ms and together() about 300 ms.",
        proof: "node v22.22.0, this session (get simulated with a 300 ms timer):\nsequential [\"A\",\"B\"] 601 ms\nconcurrent [\"A\",\"B\"] 300 ms" },
      { how: "known", sure: "high", claim: "The queue mechanics are the standard event loop model, not read from a source this session." }
    ],
    steps: [
      { cam: "far", lod: 1, loop: "idle", stack: [], bars: {},
        note: "Same machinery as before. Two functions want the same two values, and each request spends 300 ms in the host." },
      { cam: "left", lod: 1, loop: "run", stack: ["script"], line: { fn: 11 }, t: 0, bars: {},
        note: "The script notes the time and calls inTurn()." },
      { cam: "left", lod: 1, loop: "run", stack: ["script", "inTurn()"], line: { fn: 2 }, t: 0, bars: { sa: [0, 0] },
        tokens: { ja: { at: "host:0", p: 0 } },
        note: "inTurn() calls get(\"a\"). One request leaves for the host." },
      { cam: "far", lod: 1, loop: "idle", stack: [], line: { fn: 2 }, parked: { fn: [3, 4] }, t: 150, bars: { sa: [0, 150] },
        tokens: { ja: { at: "host:0", p: 0.5 }, cont: { at: "heap:0", sub: "lines 3 and 4" } },
        note: "await parks the rest of inTurn(), and the script waits on inTurn() in turn. The stack is empty and the thread is idle, yet nobody has asked for b." },
      { cam: "left", lod: 1, loop: "idle", stack: [], line: { fn: 2 }, parked: { fn: [3, 4] }, t: 150, bars: { sa: [0, 150] },
        tokens: { ja: { at: "host:0", p: 0.5 }, cont: { at: "heap:0", sub: "lines 3 and 4" } },
        predict: { q: "When does get(\"b\") start?",
          options: ["At 0 ms, together with a", "At 300 ms, when a has arrived", "As soon as the thread is idle"],
          answer: 1, why: "The call to get(\"b\") sits on line 3, inside the parked continuation. It cannot run before a arrives." } },
      { cam: "right", lod: 2, loop: "idle", stack: [], parked: { fn: [3, 4] }, t: 300, bars: { sa: [0, 300] },
        tokens: { ca: "macro:0", cont: { at: "heap:0", sub: "lines 3 and 4" } },
        note: "300 ms: a arrives. Its callback joins the task queue, resolves the promise, and the continuation passes through the microtask queue. The round trip from the first scenario." },
      { cam: "left", lod: 1, loop: "micro", stack: [], line: { fn: 3 }, t: 300, bars: { sa: [0, 300], sb: [300, 300] },
        tokens: { cont: { at: "stack:0", label: "inTurn() resumed", sub: "from line 3" }, jb: { at: "host:0", p: 0 } },
        note: "Resumed at line 3. Only now does get(\"b\") leave for the host." },
      { cam: "far", lod: 1, loop: "idle", stack: [], line: { fn: 3 }, parked: { fn: [4, 4] }, t: 450, bars: { sa: [0, 300], sb: [300, 450] },
        tokens: { cont: { at: "heap:0", sub: "line 4" }, jb: { at: "host:0", p: 0.5 } },
        note: "Parked a second time. Another 300 ms of waiting with an idle thread." },
      { cam: "left", lod: 1, loop: "micro", stack: [], line: { fn: 4 }, t: 600, bars: { sa: [0, 300], sb: [300, 600] },
        tokens: { cont: { at: "stack:0", label: "inTurn() resumed", sub: "from line 4" } },
        note: "600 ms: b arrives and inTurn() returns. Two waits, placed end to end." },
      { cam: "left", lod: 1, loop: "micro", stack: ["script"], line: { fn: 13 }, out: ["[\"A\",\"B\"] 600"], t: 0, bars: { sa: [0, 300], sb: [300, 600] },
        note: "The script prints the result and 600 ms, notes the time again, and calls together(). The clock starts again from 0." },
      { cam: "left", lod: 1, loop: "run", stack: ["script", "together()"], line: { fn: 7 }, out: ["[\"A\",\"B\"] 600"], t: 0, bars: { sa: [0, 300], sb: [300, 600], ca: [0, 0], cb: [0, 0] },
        tokens: { ja: { at: "host:0", p: 0 }, jb: { at: "host:1", p: 0 }, pa: "heap:0", pb: "heap:1" },
        note: "together() calls get(\"a\") and get(\"b\") before it awaits anything. Both requests leave in the same turn; pa and pb are pending." },
      { cam: "far", lod: 2, loop: "idle", stack: [], line: { fn: 8 }, parked: { fn: [8, 8] }, out: ["[\"A\",\"B\"] 600"], t: 150, bars: { sa: [0, 300], sb: [300, 600], ca: [0, 150], cb: [0, 150] },
        tokens: { ja: { at: "host:0", p: 0.5 }, jb: { at: "host:1", p: 0.5 }, pa: "heap:0", pb: "heap:1", cont: { at: "heap:2", sub: "waits on pa" } },
        note: "await pa parks the rest of together() on pa. The host works on both requests at the same time." },
      { cam: "right", lod: 2, loop: "idle", stack: [], line: { fn: 8 }, parked: { fn: [8, 8] }, out: ["[\"A\",\"B\"] 600"], t: 150, bars: { sa: [0, 300], sb: [300, 600], ca: [0, 150], cb: [0, 150] },
        tokens: { ja: { at: "host:0", p: 0.5 }, jb: { at: "host:1", p: 0.5 }, pa: "heap:0", pb: "heap:1", cont: { at: "heap:2", sub: "waits on pa" } },
        predict: { q: "Each request takes 300 ms. When does together() return?",
          options: ["At 150 ms", "At 300 ms", "At 600 ms"],
          answer: 1, why: "The waits overlap. JavaScript still runs one thing at a time, but waiting is not running." } },
      { cam: "queues", lod: 2, loop: "idle", stack: [], parked: { fn: [8, 8] }, out: ["[\"A\",\"B\"] 600"], t: 300, bars: { sa: [0, 300], sb: [300, 600], ca: [0, 300], cb: [0, 300] },
        tokens: { ca: "macro:0", cb: "macro:1", pa: "heap:0", pb: "heap:1", cont: { at: "heap:2", sub: "waits on pa" } },
        note: "300 ms: both callbacks arrive in the task queue, one behind the other." },
      { cam: "queues", lod: 2, loop: "micro", stack: [], line: { fn: 8 }, parked: { fn: [8, 8] }, out: ["[\"A\",\"B\"] 600"], t: 300, bars: { sa: [0, 300], sb: [300, 600], ca: [0, 300], cb: [0, 300] },
        tokens: { cb: "macro:0", pa: { at: "heap:0", sub: "fulfilled: \"A\"", state: "fulfilled" }, pb: "heap:1", cont: { at: "heap:2", sub: "waits on pb" } },
        note: "a's callback fulfills pa. The rest of together() resumes, reaches await pb, finds pb still pending, and is parked again, on pb." },
      { cam: "work", lod: 2, loop: "micro", stack: [], line: { fn: 8 }, out: ["[\"A\",\"B\"] 600"], t: 300, bars: { sa: [0, 300], sb: [300, 600], ca: [0, 300], cb: [0, 300] },
        tokens: { pa: { at: "heap:0", sub: "fulfilled: \"A\"", state: "fulfilled" }, pb: { at: "heap:1", sub: "fulfilled: \"B\"", state: "fulfilled" }, cont: { at: "stack:0", label: "together() resumed", sub: "from line 8" } },
        note: "b's callback fulfills pb, and the rest resumes again: together() returns at 300 ms." },
      { cam: "far", lod: 1, loop: "micro", stack: ["script"], line: { fn: 13 }, out: ["[\"A\",\"B\"] 600", "[\"A\",\"B\"] 300"], t: 300, bars: { sa: [0, 300], sb: [300, 600], ca: [0, 300], cb: [0, 300] },
        note: "The script prints 300 ms. The difference is where the calls sit relative to await. Start the work first, await afterwards." }
    ]
  },

  {
    id: "ordering",
    title: "What prints first",
    intro: "A 0 ms timer, a resolved promise, and plain statements.",
    code: [
      { id: "main", title: "script", lines: [
        "console.log(\"1 sync\");",
        "setTimeout(",
        "  () => console.log(\"2 timeout\"), 0);",
        "Promise.resolve().then(",
        "  () => console.log(\"3 promise\"));",
        "console.log(\"4 sync\");" ] }
    ],
    tokens: {
      job: { label: "timer 0 ms", sub: "holds the timeout callback", kind: "job", from: "stack:0" },
      tcb: { label: "timeout callback", sub: "prints \"2 timeout\"", kind: "task", from: "host:0" },
      pcb: { label: "then callback", sub: "prints \"3 promise\"", kind: "micro", from: "stack:0" },
      pr:  { label: "Promise.resolve()", sub: "fulfilled: undefined", kind: "promise", from: "stack:0" }
    },
    evidence: [
      { how: "known", sure: "medium", claim: "Spec names in the 'In the spec' sections are quoted from memory of the ECMAScript and HTML specifications; names change between editions and were not checked this session." },
      { how: "run", sure: "high", claim: "The output is 1 sync, 4 sync, 3 promise, 2 timeout.",
        proof: "node v22.22.0, this session, 20 runs, one distinct order:\n1 sync\n4 sync\n3 promise\n2 timeout" },
      { how: "known", sure: "high", claim: "Microtasks are drained after each task and before the next one. This is the HTML event loop's microtask checkpoint, not read this session." }
    ],
    steps: [
      { cam: "left", lod: 1, loop: "idle", stack: [],
        predict: { q: "Six lines, four prints. In which order do they appear?",
          options: ["1, 2, 3, 4", "1, 4, 2, 3", "1, 4, 3, 2", "1, 3, 4, 2"],
          answer: 2, why: "The next steps show why a promise overtakes a 0 ms timer." } },
      { cam: "left", lod: 1, loop: "run", stack: ["script"], line: { main: 1 }, out: ["1 sync"],
        note: "Line 1 is ordinary synchronous code. It prints at once." },
      { cam: "far", lod: 1, loop: "run", stack: ["script"], line: { main: 2 }, out: ["1 sync"],
        tokens: { job: { at: "host:0", p: 1 } },
        note: "setTimeout hands its callback to the host with a delay of 0 ms. Zero delay does not mean now." },
      { cam: "right", lod: 2, loop: "run", stack: ["script"], line: { main: 2 }, out: ["1 sync"],
        tokens: { tcb: "macro:0" },
        note: "The timer expires straight away and the host queues the callback as a task. There it waits, because the stack is busy with the script.",
        ev: [{ how: "known", sure: "medium", claim: "The exact moment the host enqueues the callback is not observable from the script and engines clamp very small delays (Node treats 0 as 1 ms). What is guaranteed is that it cannot run before the current task and its microtasks finish." }] },
      { cam: "heap", lod: 2, loop: "run", stack: ["script"], line: { main: 4 }, out: ["1 sync"],
        tokens: { tcb: "macro:0", pr: { at: "heap:0", sub: "fulfilled: undefined", state: "fulfilled" } },
        note: "Promise.resolve() creates a promise that is already fulfilled. It sits in the heap with its value and an empty list of reactions. Nothing is pending and no host is involved." },
      { cam: "heap", lod: 2, loop: "run", stack: ["script"], line: { main: 4 }, out: ["1 sync"],
        tokens: { tcb: "macro:0", pr: { at: "heap:0", sub: "fulfilled: undefined", state: "fulfilled" }, pcb: { at: "heap:1", sub: "reaction on the promise" } },
        note: "then() registers its callback as a reaction of that promise. A reaction normally waits for the promise to settle. This one is already settled, so there is nothing to wait for." },
      { cam: "queues", lod: 2, loop: "run", stack: ["script"], line: { main: 5 }, out: ["1 sync"],
        tokens: { tcb: "macro:0", pr: { at: "heap:0", sub: "fulfilled: undefined", state: "fulfilled" }, pcb: "micro:0" },
        note: "So the engine queues the reaction at once, as a microtask. At once means appended to the queue now, never run now: a reaction is never called synchronously. Promises schedule through the microtask queue; the host schedules through the task queue." },
      { cam: "left", lod: 1, loop: "run", stack: ["script"], line: { main: 6 }, out: ["1 sync", "4 sync"],
        tokens: { tcb: "macro:0", pcb: "micro:0" },
        note: "Line 6 prints 4. The script is finished and two callbacks are waiting." },
      { cam: "queues", lod: 2, loop: "idle", stack: [], out: ["1 sync", "4 sync"],
        tokens: { tcb: "macro:0", pcb: "micro:0" },
        predict: { q: "The stack is empty. The timeout callback was queued first. Which one runs first?",
          options: ["The timeout callback, it was queued first", "The promise callback", "It depends on the engine"],
          answer: 1, why: "After every task the loop empties the whole microtask queue before it takes another task." } },
      { cam: "loop", lod: 2, loop: "micro", stack: [], line: { main: 5 }, out: ["1 sync", "4 sync", "3 promise"],
        tokens: { tcb: "macro:0", pcb: "stack:0" },
        note: "Microtasks first: the then callback runs and prints 3." },
      { cam: "loop", lod: 2, loop: "run", stack: [], line: { main: 3 }, out: ["1 sync", "4 sync", "3 promise", "2 timeout"],
        tokens: { tcb: "stack:0" },
        note: "The microtask queue is empty. Now the loop takes one task: the timeout callback prints 2." },
      { cam: "far", lod: 1, loop: "idle", stack: [], out: ["1 sync", "4 sync", "3 promise", "2 timeout"],
        note: "The loop's rule: one task, then every microtask, then the next task. A promise reaction always overtakes a timer that is already waiting." }
    ]
  },

  {
    id: "blocked",
    title: "Blocking the loop",
    intro: "What happens when code never leaves the stack.",
    code: [
      { id: "main", title: "script", lines: [
        "setTimeout(",
        "  () => console.log(\"tick\"), 100);",
        "const end = Date.now() + 500;",
        "while (Date.now() < end) {}",
        "console.log(\"done\");" ] }
    ],
    tokens: {
      job:   { label: "timer 100 ms", sub: "holds the tick callback", kind: "job", from: "stack:0" },
      tcb:   { label: "timer callback", sub: "prints \"tick\"", kind: "task", from: "host:0" },
      click: { label: "click handler", sub: "user clicked at 300 ms", kind: "task", from: "host:1" }
    },
    bars: { max: 600, rows: [
      { id: "spin", label: "while loop on the stack" }, { id: "wait", label: "tick waits in the queue" } ] },
    evidence: [
      { how: "known", sure: "medium", claim: "Spec names in the 'In the spec' sections are quoted from memory of the ECMAScript and HTML specifications; names change between editions and were not checked this session." },
      { how: "run", sure: "high", claim: "done prints at 500 ms and tick only after it, although its timer was set to 100 ms.",
        proof: "node v22.22.0, this session:\ndone at 500 ms\ntick at 506 ms" },
      { how: "known", sure: "high", claim: "The click in this scenario is a browser illustration and was not run. That input events queue as tasks behind a busy stack is standard browser behaviour, not read this session." }
    ],
    steps: [
      { cam: "far", lod: 1, loop: "idle", stack: [], bars: {},
        note: "Every await opens a gap in which the loop can run something else. This script has no gaps." },
      { cam: "far", lod: 1, loop: "run", stack: ["script"], line: { main: 1 }, t: 0, bars: {},
        tokens: { job: { at: "host:0", p: 0 } },
        note: "A 100 ms timer goes to the host." },
      { cam: "left", lod: 1, loop: "blocked", stack: ["script"], line: { main: 4 }, t: 50, bars: { spin: [0, 50] },
        tokens: { job: { at: "host:0", p: 0.5 } },
        note: "Line 4 spins for 500 ms. It never awaits and never returns, so the script's frame stays on the stack." },
      { cam: "right", lod: 2, loop: "blocked", stack: ["script"], line: { main: 4 }, t: 100, bars: { spin: [0, 100], wait: [100, 100] },
        tokens: { tcb: "macro:0" },
        note: "100 ms: the timer fires on time. The host does its part and queues the callback." },
      { cam: "queues", lod: 2, loop: "blocked", stack: ["script"], line: { main: 4 }, t: 100, bars: { spin: [0, 100], wait: [100, 100] },
        tokens: { tcb: "macro:0" },
        predict: { q: "The callback has been in the task queue since 100 ms. When does tick print?",
          options: ["At 100 ms", "At about 500 ms", "Never"],
          answer: 1, why: "The loop can take a task only when the stack is empty. Until line 4 finishes, nothing else runs." } },
      { cam: "right", lod: 2, loop: "blocked", stack: ["script"], line: { main: 4 }, t: 300, bars: { spin: [0, 300], wait: [100, 300] },
        tokens: { tcb: "macro:0", click: "macro:1" },
        note: "300 ms. In a browser, a click arriving now queues behind the timer. The page cannot respond or repaint, because the event loop is not turning." },
      { cam: "left", lod: 1, loop: "run", stack: ["script"], line: { main: 5 }, out: ["done"], t: 500, bars: { spin: [0, 500], wait: [100, 500] },
        tokens: { tcb: "macro:0", click: "macro:1" },
        note: "500 ms: the while loop ends and line 5 prints done." },
      { cam: "loop", lod: 2, loop: "run", stack: [], line: { main: 2 }, out: ["done", "tick"], t: 500, bars: { spin: [0, 500], wait: [100, 500] },
        tokens: { tcb: "stack:0", click: "macro:0" },
        note: "The stack empties and the loop finally takes the timer callback. tick prints at about 500 ms, 400 ms late." },
      { cam: "far", lod: 1, loop: "run", stack: [], out: ["done", "tick"], t: 500, bars: { spin: [0, 500], wait: [100, 500] },
        tokens: { click: "stack:0" },
        note: "Then the click. Async code is cooperative: an await is a gap for everyone else, and CPU work without gaps blocks everyone. Split the work into pieces or move it to a worker." }
    ]
  }
];

/* Longer explanation per step, shown below the key points when the text area is scrolled.
   MORE[scenario id][step index] = { how, trap, term, tryit }
   how:   the mechanism behind this step      trap: a common misconception
   term:  the name the specifications use     tryit: a small variation to predict */
window.MORE = {
  anatomy: [
    { how: "A JavaScript program is three cooperating parts. Your code is data for the runtime; the runtime is one thread with a stack and two queues; the host is everything that thread delegates waiting to.",
      trap: "The browser and the JavaScript engine are not the same thing. V8 or SpiderMonkey runs your code; the browser around it owns timers, network and the screen.",
      term: "ECMAScript specifies the runtime (agent, job queues); HTML specifies the event loop and the host's task sources." },
    { how: "Source code is executed statement by statement inside a frame. A function call creates a new frame; a return destroys it. console.log writes synchronously, so the console is a trace of the order in which lines ran.",
      trap: "Text order is execution order only within one synchronous run. Across tasks it tells you nothing, which is what the later scenarios are about.",
      term: "The spec calls the running code's state an execution context; the line being evaluated is its code evaluation state." },
    { how: "The stack grows when a function is called and shrinks when it returns. The engine executes only the top frame. Because there is one stack per thread, the stack being non-empty means the thread is busy.",
      trap: "Nothing can interrupt a frame. No timer, click or promise can insert itself while the stack is non-empty.",
      term: "Execution context stack; the running execution context is its top. Run-to-completion is the consequence." },
    { how: "Frames are temporary; the heap is where values live as long as something refers to them. A closure keeps its variables here after its frame is gone, and a parked async function is exactly such a closure plus a saved position.",
      trap: "A promise in the heap is inert. Nothing inside it is executing; it waits for someone to call its resolve function.",
      term: "Promise objects carry [[PromiseState]], [[PromiseResult]] and reaction lists; the parked rest of an async function is its suspended execution context." },
    { how: "When a promise settles, every reaction registered on it is wrapped in a job and appended here. The loop drains the queue fully, including microtasks added during draining, before looking at the task queue.",
      trap: "The microtask queue is not a fast lane for important work. It is simply where promise reactions go, and it starves tasks if it never empties.",
      term: "ECMAScript: the job queue, filled by HostEnqueuePromiseJob. HTML: the microtask queue, drained at a microtask checkpoint." },
    { how: "Every result from outside JavaScript enters as a task: a timer expiring, bytes arriving, a key pressed. The host appends; the loop removes one at a time. Between two tasks the loop drains microtasks and may render a frame.",
      trap: "A task waits for its turn even when the thread is idle at the moment it is queued; the loop still has to come round.",
      term: "HTML: task queues per task source (timers, networking, user interaction). Node: libuv phases such as timers, poll, check." },
    { how: "The loop is a simple cycle with no priorities beyond the two queues: take one task, run it to completion, drain the microtasks, repeat. Everything about ordering in JavaScript follows from this cycle.",
      trap: "The loop does not run 'in the background'. It runs on the same thread, between your tasks; when your code is on the stack, the loop is paused.",
      term: "HTML event loop processing model; a 'turn' or 'tick' is one pass through it." },
    { how: "The host has its own threads and talks to the operating system. A timer is a deadline in a timer heap; a fetch is a socket in a network stack. When any of them completes, the host cannot call JavaScript directly; it queues a task and waits for the loop.",
      trap: "The host doing things concurrently does not make JavaScript multithreaded. The boundary is the task queue, and it is crossed one task at a time.",
      term: "HTML calls this side the user agent and its parallel work 'in parallel' steps; Node's host layer is libuv with a thread pool for file I/O." },
    { how: "Four moves cover everything: call pushes a frame; settle queues a microtask; host queues a task; loop pops a task or microtask onto the stack. await is the first and second move in sequence, with the engine doing the bookkeeping.",
      trap: "There is no fifth move. If you think something 'just happened', it was one of these four.",
      term: "These correspond to the spec's call and return, TriggerPromiseReactions, queue a task, and the event loop processing model." }
  ],
  roundtrip: [
    { how: "Everything in this animation happens on one JavaScript thread. The front sheet is what you write, the middle sheet is what the engine keeps (stack, heap, two queues, the loop), and the back sheet is machinery that is not JavaScript at all: timers, sockets, files, the screen.",
      trap: "Async JavaScript does not run your code on several threads. It runs one piece of your code at a time and uses the host to wait.",
      term: "The HTML standard calls the middle machinery the event loop and the back sheet the agent's host or user agent. In Node the host is libuv plus the operating system." },
    { how: "A script is itself a task. The event loop took it from the task queue and pushed a frame for it. Everything the script calls synchronously stacks on top of that frame.",
      trap: "Line 6 does not spawn anything. Calling an async function is an ordinary synchronous call; what is special is only how it returns.",
      term: "The ECMAScript spec calls a frame an execution context; the stack is the execution context stack." },
    { how: "Up to the first await, an async function runs synchronously inside its caller. The console shows A before anything else because nothing has yielded yet.",
      trap: "Students often expect async functions to start later. They start at once; they only stop early.",
      term: "The spec starts the body with AsyncFunctionStart, which runs it synchronously until the first Await." },
    { how: "new Promise runs its executor at once. The executor registers a timer with the host and returns; the promise object stays in the heap with state pending. The host now owns the 300 ms, not JavaScript.",
      trap: "A pending promise is not a running thing. It is a record with a state and a list of reactions. Nothing is computing inside it.",
      term: "The promise's internal slots are [[PromiseState]] and [[PromiseFulfillReactions]]. The timer is a task source in HTML terms." },
    { how: "At this point load() has two frames above the script and a pending promise in its hands. The question is what await does with a value that is not ready.",
      trap: "The word await suggests blocking. It never blocks the thread. It suspends only this function.",
      term: "Await is an abstract operation: it wraps the operand with PromiseResolve, attaches fulfil and reject closures with PerformPromiseThen, and suspends the running execution context." },
    { how: "The function's remaining work, including its local variables, becomes a reaction attached to p. The engine pops load()'s frame and makes load() return a second promise, the one its caller holds. When p fulfils, the reaction will queue a microtask that pushes a fresh frame and continues at line 4.",
      trap: "await does not copy the function or restart it. It saves exactly the point of suspension, like a bookmark, and the locals stay alive in the heap.",
      term: "The parked rest is the function's continuation. The spec keeps it as the async function's suspended execution context, resumed from a promise reaction job." },
    { how: "Control returned to the script at line 6 and moved on. The script does not know or care that load() is suspended; it only holds a pending promise it ignores.",
      trap: "Line 7 is not 'running in parallel' with load(). load() has no frame at all right now. One thing is running: the script.",
      term: "The script is still the same task. HTML calls the whole run, from the loop taking it to the stack emptying, a task's steps." },
    { how: "The stack is empty, so the loop moves to its waiting state. The host runs the timer on its own clock. In a browser this is a timer thread; in Node libuv keeps a timer heap and polls it between loop phases.",
      trap: "An empty stack with an idle loop is not the program being finished. The host still has work in flight, and the process stays alive for it.",
      term: "Node keeps the loop alive while there are active handles; a pending timer is one. Browsers never exit; the page just idles." },
    { how: "When the timer expires, the host wraps the callback in a task and appends it to the task queue. It does not touch the stack: only the event loop pushes frames. The callback waits for its turn even though nothing else is running.",
      trap: "The timer firing and the callback running are two different moments. The delay is a lower bound for when the callback is queued, never a guarantee for when it runs.",
      term: "HTML: the timer task is queued on the timer task source. Node: the timers phase of the loop runs expired timer callbacks." },
    { how: "The loop pops one task and pushes its frame. Inside, res(\"Ada\") settles p: its state becomes fulfilled with the value, and every reaction registered on p is scheduled as a microtask. The reaction here is load()'s continuation.",
      trap: "Resolving a promise does not run its reactions immediately, even though the resolver is on the stack right now. They always go through the microtask queue.",
      term: "The spec calls this TriggerPromiseReactions, which enqueues a PromiseReactionJob on the job queue (HTML: a microtask)." },
    { how: "The timer task returns and the stack empties. Before taking any new task, the loop performs a microtask checkpoint: it runs every microtask, including ones added while draining. The continuation runs with user bound to \"Ada\" and line 4 prints C.",
      trap: "Resuming does not happen 'as soon as the promise fulfils' in wall-clock terms. It happens at the checkpoint after the current task, which is normally microseconds later but can be seconds if the task is long.",
      term: "HTML: perform a microtask checkpoint. ECMAScript: a PromiseReactionJob whose handler resumes the async function's execution context." },
    { how: "The whole trip: suspend at await, promise fulfilled from a task, continuation queued as a microtask, frame rebuilt on the empty stack. The function-level view hides four hand-overs; the engine-level view shows them all.",
      trap: "await is not a separate concurrency mechanism. It is callbacks and promises with the bookkeeping done by the compiler.",
      term: "In spec terms an async function is a generator-like state machine driven by promise reactions; TypeScript's downlevel output makes that literal." }
  ],
  overlap: [
    { how: "get() behaves like fetchUser() in the first scenario: it returns a pending promise and leaves a 300 ms job with the host. The question is only when each call happens relative to the awaits.",
      trap: "await Promise.all is not 'parallel JavaScript'. The parallelism is in the host, where two requests can be in flight; JavaScript still runs one continuation at a time.",
      term: "The bars at the bottom are a timeline, which is how profilers show this: each bar is the interval between a request leaving and its callback arriving." },
    { how: "inTurn() runs synchronously until the first await. That means get(\"a\") is called, but get(\"b\") on line 3 has not been reached yet.",
      trap: "The order of lines is the order of calls. Nothing on line 3 can start before line 2 has produced a value.",
      term: "This is ordinary sequential evaluation; await just inserts a suspension point between the two calls." },
    { how: "The continuation is parked, the stack is empty, and the loop waits. The host is busy with one request. The thread could run other tasks here, but this function cannot progress.",
      trap: "An idle thread is not the same as an idle program. The program is waiting on a dependency it created for itself.",
      term: "Profilers call this gap idle time; in request handlers it shows up as latency without CPU use." },
    { how: "The call to get(\"b\") is written after the await, so it is part of the parked code. Until the continuation is resumed, that line does not exist for the engine.",
      trap: "There is no look-ahead. The engine does not scan the function to find independent calls and start them early.",
      term: "Compilers call this a data dependency; here the dependency is artificial, created by the position of await." },
    { how: "The callback for a arrives as a task, resolves promise a, and the parked continuation is queued as a microtask. Same round trip as scenario one, compressed to a single step.",
      trap: "The 300 ms is spent in the host, not in the queue. The queue hop costs microseconds.",
      term: "Task, then microtask checkpoint, then the continuation: the standard sequence." },
    { how: "inTurn() resumes at line 3 and only now calls get(\"b\"). The second 300 ms begins at the 300 ms mark.",
      trap: "The second request was not slowed down by anything. It simply started late.",
      term: "The timeline shows two bars end to end; profilers call this a waterfall." },
    { how: "Parked again, now on promise b. The continuation is a different object from the first one: each await creates a new reaction.",
      trap: "The function is not 'still waiting since 0 ms'. It ran, returned, and is suspended a second time.",
      term: "Each Await creates a fresh PromiseCapability and reaction; nothing is reused." },
    { how: "At 600 ms the second callback arrives, the continuation resumes at line 4, and the function returns. Its own promise fulfils with [a, b], which would queue any awaiting caller as a microtask.",
      trap: "The return value is not available 'when the function ends' to a synchronous caller. It is only available through the promise.",
      term: "In the spec, AsyncBlockStart catches the body's completion and calls the function promise's resolve function with the returned value." },
    { how: "together() calls get(\"a\") and get(\"b\") on line 7, before any await. Both executors run and both timers are registered: two jobs are in the host, and pa and pb are pending.",
      trap: "An await does not start anything. The requests started when get() was called; await only waits on a promise that already exists.",
      term: "Promise.all([get(\"a\"), get(\"b\")]) would do the same with one combined promise; the session's conclusion names it." },
    { how: "await pa parks the rest of together() on pa. In the host, two jobs run side by side on its own threads or in the operating system.",
      trap: "The host doing two things at once does not break the single-thread rule. The rule is about JavaScript frames, not about what the host does meanwhile.",
      term: "The rest is registered as a reaction of pa; pb has no reaction yet." },
    { how: "Both bars grow at the same time. The total wait equals the longest request, not the sum.",
      trap: "The requests are not 'sharing' the 300 ms. Each takes its full 300 ms; they overlap.",
      term: "In queueing terms this is parallel I/O with a fan-in; latency is max rather than sum." },
    { how: "Two tasks arrive, one per callback, one behind the other.",
      trap: "The order of arrival in the queue is not guaranteed; a and b could be swapped. The result array keeps the order of the text regardless: [await pa, await pb].",
      term: "Each callback is a task; what it resumes goes to the microtask queue, emptied before the next task." },
    { how: "a's callback fulfills pa; the microtask queue is emptied before b's task: the rest of together() resumes, reaches await pb, and parks again, now on pb.",
      trap: "Two awaits on two promises that are both under way cost no extra waiting: the second park lasts only until b's task, already in the queue.",
      term: "Each await registers a fresh reaction on the promise it awaits." },
    { how: "The continuation resumes at line 8 and returns [a, b]. Node measured the two functions at 601 ms and 300 ms in this session.",
      trap: "The speed-up did not come from more CPU. It came from asking earlier.",
      term: "The pattern is sometimes called 'start, then await'. Linters flag the sequential form as no-await-in-loop when it occurs in loops." },
    { how: "The two functions differ by where the calls sit relative to await. The engine does the rest.",
      trap: "Adding async to a function does not make it faster. Only moving the awaits does.",
      term: "The general rule in the Node and MDN guides: start independent work before awaiting any of it." }
  ],
  ordering: [
    { how: "Four prints, three mechanisms: synchronous code, a timer through the host, and a promise reaction through the microtask queue. The order follows from the rule the event loop applies between tasks.",
      trap: "A 0 ms timer and an already-resolved promise look equally 'immediate'. They take different routes.",
      term: "This is the classic microtask versus macrotask question; the HTML spec only says task and microtask." },
    { how: "Ordinary statements run as part of the script task. Nothing can interleave with them.",
      trap: "No async code has started yet, because none has been reached.",
      term: "Script evaluation is itself a task; its steps run to completion." },
    { how: "setTimeout registers the callback with the host. The host owns it from here; JavaScript keeps no reference it will call.",
      trap: "Zero delay means 'as soon as the loop gets round to it', not 'now'. Browsers also clamp nested timers to at least 4 ms, and Node treats 0 as 1 ms.",
      term: "HTML's timer initialisation steps; the callback is queued on the timer task source after the delay." },
    { how: "The timer expires and the host appends a task. Only the event loop can take that task, and the loop is busy with the script.",
      trap: "The callback being queued is not the same as it running. The queue is a waiting room.",
      term: "Queued task; the loop will pick it in a later iteration." },
    { how: "Promise.resolve(v) returns a promise whose [[PromiseState]] is already fulfilled and whose value is v. Creating it involves no timer, no host and no waiting; it is a heap object like any other.",
      trap: "A fulfilled promise is not 'done running'. It never ran anything. It is a container that already holds its value.",
      term: "Promise.resolve calls PromiseResolve, which returns the argument unchanged if it is already a promise and otherwise creates a resolved promise." },
    { how: "then(onFulfilled) creates a reaction record and would normally append it to the promise's [[PromiseFulfillReactions]] list, to be triggered when the promise settles. The settle event is what normally moves a reaction into the queue.",
      trap: "Registering a reaction and running it are different moments even when the promise is already fulfilled.",
      term: "PerformPromiseThen builds a PromiseReaction record; for a pending promise it is stored, for a settled one it is enqueued." },
    { how: "Because the promise is already fulfilled, PerformPromiseThen skips the list and enqueues a PromiseReactionJob immediately. Enqueue means append to the microtask queue. The job runs at the next microtask checkpoint, after the current task.",
      trap: "The then callback is not called synchronously even though the promise is already fulfilled. Reactions always go through the microtask queue; that is what makes then() predictable.",
      term: "PerformPromiseThen on a fulfilled promise calls HostEnqueuePromiseJob at once; HTML implements that job as a microtask." },
    { how: "The script's last statement runs. The task is about to end with both queues non-empty.",
      trap: "The script did not 'finish' the async work. It finished its own task.",
      term: "End of the task's steps; the loop now performs its checkpoint." },
    { how: "Two things wait: a task from the timer and a microtask from the promise. The loop's rule decides, not the order they were queued in.",
      trap: "First in, first out holds within one queue, not across the two.",
      term: "Microtask checkpoint before the next task." },
    { how: "After the script task, the loop drains the microtask queue completely. The then callback runs and prints 3.",
      trap: "Draining is complete: microtasks that enqueue more microtasks also run now. An endless chain of microtasks would starve every task forever.",
      term: "Microtask queue draining loop in the HTML spec; the ECMAScript job queue." },
    { how: "The microtask queue is empty, so the loop takes one task: the timer callback. It prints 2.",
      trap: "The timer did not 'lose a race'. It was never in the same queue.",
      term: "One task per loop iteration; then a checkpoint; then the next task." },
    { how: "Promise reactions are microtasks and always run before the next task. Timers, I/O and events are tasks and wait for the loop to come round.",
      trap: "The rule is not 'promises are faster'. It is 'microtasks are drained between tasks'.",
      term: "Node adds process.nextTick, which runs even before promise microtasks; setImmediate runs after I/O, as a task." }
  ],
  blocked: [
    { how: "Every await is a point at which the loop can run other tasks. A script that never awaits and never returns gives the loop nothing to do but wait for it.",
      trap: "Timers do not interrupt. They queue.",
      term: "The property is called cooperative scheduling: the running code decides when others may run." },
    { how: "The timer is registered and the host starts counting. So far this looks exactly like scenario one.",
      trap: "Setting a 100 ms timer does not reserve the thread at 100 ms.",
      term: "Timer task source, delay 100 ms." },
    { how: "The while loop keeps the script's frame on the stack and burns CPU. No await, no return, no gap.",
      trap: "The loop is not 'blocking the timer'. The timer still runs in the host. What it blocks is the loop's ability to pick up the callback.",
      term: "Long task: Chrome's profiler flags any task over 50 ms." },
    { how: "At 100 ms the host does its job: the callback is queued. The host does not care that the stack is busy.",
      trap: "The timer did not fire late. It fired on time; the callback is what will be late.",
      term: "The task is queued; HTML allows the loop to run it only when the stack is empty." },
    { how: "The task queue holds the callback and the loop cannot take it: the loop takes a task only after the current one completes.",
      trap: "Nothing in JavaScript can pre-empt a running task. Not timers, not promises, not user input.",
      term: "Run-to-completion semantics." },
    { how: "A click handler is just another task on the queue. While the stack is busy, the page cannot handle input, cannot run its promise reactions, and cannot paint: rendering also waits for the loop.",
      trap: "The page is not 'slow'. It is frozen: no frames are produced at all until the task ends.",
      term: "HTML's rendering opportunity sits in the loop; a long task blocks it. Browsers show 'page unresponsive' after a few seconds." },
    { how: "The loop ends, line 5 prints done, and the script task finishes. The stack empties for the first time since the start.",
      trap: "done printed first although it was written last. Textual order within one task wins over any timer.",
      term: "End of the task; the loop may now continue." },
    { how: "The loop takes the oldest task: the timer callback, waiting since 100 ms. It runs at about 500 ms. Node measured 506 ms in this session.",
      trap: "No part of the system was slow. Every component did its job on time; the thread was simply taken.",
      term: "Timer lateness is what long-task metrics measure; browsers report it as input delay." },
    { how: "Then the click runs. Async code only works when every task is short enough to leave gaps. CPU-heavy work has to be chunked across awaits or moved to a worker thread, which has its own loop.",
      trap: "Wrapping CPU work in a promise or an async function does not move it off the thread. Only a worker does.",
      term: "Web Workers and Node worker_threads: separate threads with separate event loops, communicating by messages." }
  ]
};

/* Runnable "Try it" per step. TRY[scenario id][step index] = { q, code }
   The page runs code in the browser with a captured console. Helpers available inside:
   get(k, ms = 300)  a promise that resolves to k.toUpperCase() after ms, through a timer in the host
   spin(ms)          a busy wait that keeps the stack occupied for ms
   Measured Node output is stored in tryout.js (generated) as fallback and as evidence. */
window.TRY = {
  anatomy: [
    { q: "One line per sheet: a plain statement, a promise, a timer. Predict the order before you run.",
      code: 'console.log("code sheet: runs now");\nPromise.resolve().then(() => console.log("runtime: microtask"));\nsetTimeout(() => console.log("host: task from a timer"), 0);' },
    { q: "Nested calls: in which order do the four lines print?",
      code: 'function a() { console.log("a starts"); b(); console.log("a ends"); }\nfunction b() { console.log("b runs on top of a"); }\na();\nconsole.log("script ends");' },
    { q: "Can a timer interrupt a frame? The timer is due at 10 ms; the loop keeps the stack busy for 200 ms.",
      code: 'setTimeout(() => console.log("timer wanted to run at 10 ms"), 10);\nspin(200);\nconsole.log("frame finished at 200 ms");' },
    { q: "A closure outlives its frame. Where does n live after counter() has returned?",
      code: 'function counter() { let n = 0; return () => ++n; }\nconst next = counter();   // counter\'s frame is gone\nconsole.log(next(), next(), next());' },
    { q: "Who can enqueue a microtask? Two ways, same queue.",
      code: 'Promise.resolve().then(() => console.log("promise reaction"));\nqueueMicrotask(() => console.log("queueMicrotask"));\nconsole.log("sync first");' },
    { q: "The host's door: a timer with delay 0 still comes in as a task.",
      code: 'setTimeout(() => console.log("task from the host"), 0);\nconsole.log("the script task is still running");' },
    { q: "One full turn of the loop: task, then all microtasks, then the next task.",
      code: 'setTimeout(() => console.log("task 2"), 0);\nqueueMicrotask(() => console.log("microtask after task 1"));\nconsole.log("task 1 (the script)");' },
    { q: "The host keeps counting while JavaScript is busy. Compare when the timer was due with when it ran.",
      code: 'const t0 = Date.now();\nsetTimeout(() => console.log("timer due at 100, ran at", Date.now() - t0), 100);\nspin(250);\nconsole.log("JavaScript was busy until", Date.now() - t0);' },
    { q: "All four moves in one program. Label each printed line with the move that caused it.",
      code: 'async function f() {\n  console.log("call: frame pushed");\n  await get("x", 50);\n  console.log("settle + loop: microtask resumed me");\n}\nf();\nsetTimeout(() => console.log("host + loop: task ran"), 100);\nconsole.log("return: back in the script");' }
  ],
  roundtrip: [
    { q: "Count the awaits, then run: each one hands the thread back once.",
      code: 'async function f() {\n  console.log("before");\n  await null;\n  console.log("after one await");\n  await null;\n  console.log("after two awaits");\n}\nf();\nconsole.log("script end");' },
    { q: "Make load() a plain function. Which lines run before B?",
      code: 'function load() {\n  console.log("A");\n  const user = "Ada";   // no await\n  console.log("C", user);\n}\nload();\nconsole.log("B");' },
    { q: "Move the first log after the await. Which letter prints first now?",
      code: 'async function load() {\n  const user = await get("ada");\n  console.log("A");\n  console.log("C", user);\n}\nload();\nconsole.log("B");' },
    { q: "Spend the 300 ms on the stack instead of in the host. When does B print?",
      code: 'const fetchUser = () =>\n  new Promise(res => { spin(300); res("Ada"); });\nasync function load() {\n  console.log("A");\n  console.log("C", await fetchUser());\n}\nload();\nconsole.log("B");' },
    { q: "What has printed when the script’s own task and its microtasks are over?",
      code: 'async function load() {\n  console.log("A");\n  await get("x");\n  console.log("C");\n}\nload();\nconsole.log("B");\nqueueMicrotask(() => console.log("-- end of the script task --"));' },
    { q: "Two awaits in a row: how many times does load() park and resume?",
      code: 'async function load() {\n  console.log("start");\n  await get("a", 100);\n  console.log("resumed 1");\n  await get("b", 100);\n  console.log("resumed 2");\n}\nload();\nconsole.log("script end");' },
    { q: "A 300 ms busy loop after the call. The timer is only 50 ms. When does C print?",
      code: 'async function load() {\n  console.log("A");\n  await get("x", 50);\n  console.log("C");\n}\nload();\nspin(300);\nconsole.log("B");' },
    { q: "Two timers keep the loop alive. Watch the clock column.",
      code: 'setTimeout(() => console.log("short timer"), 100);\nsetTimeout(() => console.log("long timer"), 400);\nconsole.log("script end");' },
    { q: "Timers of 300 ms and 100 ms, registered in that order. Which callback is queued first?",
      code: 'setTimeout(() => console.log("300 ms timer"), 300);\nsetTimeout(() => console.log("100 ms timer"), 100);' },
    { q: "Call the resolver twice. Which value does the promise hold?",
      code: 'const p = new Promise(res => { res("first"); res("second"); });\np.then(v => console.log("value:", v));' },
    { q: "Add a .then after load(). Where does D go?",
      code: 'async function load() {\n  console.log("A");\n  await get("x", 50);\n  console.log("C");\n}\nload().then(() => console.log("D"));\nconsole.log("B");' },
    { q: "The same program written with .then instead of await. Same order?",
      code: 'function load() {\n  console.log("A");\n  return get("ada").then(user => console.log("C", user));\n}\nload();\nconsole.log("B");' }
  ],
  overlap: [
    { q: "Guess both totals, then run. The clock column shows when each finished.",
      code: 'async function inTurn() {\n  const a = await get("a");\n  const b = await get("b");\n  return [a, b];\n}\nasync function together() {\n  return Promise.all([get("a"), get("b")]);\n}\n(async () => {\n  console.log("sequential", await inTurn());\n  console.log("concurrent", await together());\n})();' },
    { q: "Swap the two awaits. Does the total change?",
      code: '(async () => {\n  const b = await get("b");\n  const a = await get("a");\n  console.log("done", a, b);\n})();' },
    { q: "What can run in the gap while a is in flight? A 150 ms timer.",
      code: '(async () => {\n  await get("a");\n  console.log("a arrived");\n})();\nsetTimeout(() => console.log("something else ran in the gap"), 150);' },
    { q: "Does the engine send b early? Log the moment each request leaves.",
      code: 'const g = k => { console.log("request", k, "sent"); return get(k); };\n(async () => {\n  await g("a");\n  await g("b");\n})();' },
    { q: "a takes 10 ms and b takes 300 ms, awaited in sequence. Total?",
      code: '(async () => {\n  await get("a", 10);\n  await get("b", 300);\n  console.log("done");\n})();' },
    { q: "Three sequential awaits of 200 ms each.",
      code: '(async () => {\n  for (const k of ["a", "b", "c"]) await get(k, 200);\n  console.log("done");\n})();' },
    { q: "Is the function still running while it waits? Ask from outside.",
      code: 'let state = "not started";\n(async () => {\n  state = "running";\n  await get("a", 100);\n  state = "finished";\n})();\nconsole.log("right after the call:", state);\nsetTimeout(() => console.log("at 50 ms:", state), 50);\nsetTimeout(() => console.log("at 150 ms:", state), 150);' },
    { q: "Measure the sequential version yourself.",
      code: 'const t0 = Date.now();\n(async () => {\n  await get("a");\n  await get("b");\n  console.log("took", Date.now() - t0, "ms");\n})();' },
    { q: "Start first, await later, without Promise.all.",
      code: '(async () => {\n  const pa = get("a"), pb = get("b");\n  const a = await pa;\n  const b = await pb;\n  console.log("both", a, b);\n})();' },
    { q: "One input rejects at 100 ms while the other needs 300 ms. When does the function resume?",
      code: 'const fail = ms => new Promise((_, rej) =>\n  setTimeout(() => rej(new Error("boom")), ms));\n(async () => {\n  try { await Promise.all([get("a", 300), fail(100)]); }\n  catch (e) { console.log("caught", e.message); }\n})();' },
    { q: "Ten requests of 300 ms at once.",
      code: 'const ps = [];\nfor (let i = 0; i < 10; i++) ps.push(get("r" + i));\nPromise.all(ps).then(r => console.log(r.length, "results"));' },
    { q: "Promise.race: which arrival resumes the function?",
      code: '(async () => {\n  const first = await Promise.race([get("slow", 300), get("fast", 100)]);\n  console.log("first:", first);\n})();' },
    { q: "Three requests in a loop, made concurrent with map.",
      code: '(async () => {\n  const results = await Promise.all(["a", "b", "c"].map(k => get(k, 200)));\n  console.log(results);\n})();' },
    { q: "Edit this: paste a sequential chain from your own code, then make it concurrent.",
      code: '(async () => {\n  const a = await get("a", 100);\n  const b = await get("b", 100);\n  console.log(a, b);\n})();' }
  ],
  ordering: [
    { q: "Run the program itself.",
      code: 'console.log("1 sync");\nsetTimeout(() => console.log("2 timeout"), 0);\nPromise.resolve().then(() => console.log("3 promise"));\nconsole.log("4 sync");' },
    { q: "Make the first line slow. Does anything overtake it?",
      code: 'spin(200);\nconsole.log("1 sync, after 200 ms");\nsetTimeout(() => console.log("2 timeout"), 0);\nPromise.resolve().then(() => console.log("3 promise"));\nconsole.log("4 sync");' },
    { q: "Delay 0, then a busy loop. When does the timer run?",
      code: 'setTimeout(() => console.log("timer"), 0);\nspin(300);\nconsole.log("after the busy loop");' },
    { q: "Two 0 ms timers, registered in opposite textual order.",
      code: 'setTimeout(() => console.log("registered first"), 0);\nsetTimeout(() => console.log("registered second"), 0);' },
    { q: "then() on an already fulfilled promise: is the callback run right away?",
      code: 'const p = Promise.resolve(42);\np.then(v => console.log("then got", v));\nconsole.log("this line is after then() in the text");' },
    { q: "Register a reaction before the promise settles, and another after. Same route?",
      code: 'const later = new Promise(res => setTimeout(() => res("settled at 100 ms"), 100));\nlater.then(v => console.log("A, registered before settling:", v));\nsetTimeout(() => later.then(v => console.log("B, registered after settling:", v)), 200);' },
    { q: "queueMicrotask instead of then. Same queue?",
      code: 'console.log("1 sync");\nsetTimeout(() => console.log("2 timeout"), 0);\nqueueMicrotask(() => console.log("3 microtask"));\nconsole.log("4 sync");' },
    { q: "Add a fifth print at the end of the script.",
      code: 'console.log("1 sync");\nsetTimeout(() => console.log("2 timeout"), 0);\nPromise.resolve().then(() => console.log("3 promise"));\nconsole.log("4 sync");\nconsole.log("5 sync");' },
    { q: "A microtask that queues another microtask. Does the task get in between?",
      code: 'setTimeout(() => console.log("task"), 0);\nqueueMicrotask(() => {\n  console.log("micro 1");\n  queueMicrotask(() => console.log("micro 2, queued by micro 1"));\n});' },
    { q: "A chain of three thens against one timer.",
      code: 'setTimeout(() => console.log("timer"), 0);\nPromise.resolve()\n  .then(() => console.log("then 1"))\n  .then(() => console.log("then 2"))\n  .then(() => console.log("then 3"));' },
    { q: "Register the promise before the timer. Does the output change?",
      code: 'console.log("1 sync");\nPromise.resolve().then(() => console.log("3 promise"));\nsetTimeout(() => console.log("2 timeout"), 0);\nconsole.log("4 sync");' },
    { q: "A task that queues a microtask: where does that microtask run?",
      code: 'setTimeout(() => {\n  console.log("task 1");\n  queueMicrotask(() => console.log("micro from task 1"));\n}, 0);\nsetTimeout(() => console.log("task 2"), 0);' }
  ],
  blocked: [
    { q: "Run the script and watch the clock column.",
      code: 'setTimeout(() => console.log("tick"), 100);\nspin(500);\nconsole.log("done");' },
    { q: "With an empty stack, how early can tick print?",
      code: 'setTimeout(() => console.log("tick"), 100);\nconsole.log("script end");' },
    { q: "Replace the busy loop with an await of a timer.",
      code: 'setTimeout(() => console.log("tick"), 100);\n(async () => {\n  await get("sleep", 500);\n  console.log("done");\n})();' },
    { q: "Measure the lateness: scheduled for 100 ms, ran when?",
      code: 'const t0 = Date.now();\nsetTimeout(() => console.log("tick ran", Date.now() - t0, "ms after scheduling"), 100);\nspin(400);' },
    { q: "Would a microtask get through earlier than a task?",
      code: 'queueMicrotask(() => console.log("microtask"));\nsetTimeout(() => console.log("task"), 0);\nspin(300);\nconsole.log("busy loop finished");' },
    { q: "Two tasks queue up behind the loop. In which order do they run?",
      code: 'setTimeout(() => console.log("timer A, due at 50"), 50);\nsetTimeout(() => console.log("timer B, due at 100"), 100);\nspin(300);\nconsole.log("busy loop finished");' },
    { q: "A timer set before the loop: does done still print first?",
      code: 'setTimeout(() => console.log("tick"), 10);\nspin(300);\nconsole.log("done");' },
    { q: "Timer of 400 ms against a busy loop of 500 ms.",
      code: 'setTimeout(() => console.log("tick, due at 400"), 400);\nspin(500);\nconsole.log("done at 500");' },
    { q: "Chunk the work with a 0 ms timer between pieces. Does tick get through?",
      code: 'setTimeout(() => console.log("tick, due at 100"), 100);\nlet left = 5;\nfunction chunk() {\n  spin(100);\n  console.log("chunk done, left:", --left);\n  if (left) setTimeout(chunk, 0);\n}\nchunk();' }
  ]
};

/* Demo 2 gained three steps (the script calls inTurn, prints and calls together; together parks a second time):
   each note above keeps the step it was written for. */
(function () {
  var more = [0, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16], tryit = [0, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 15, 16];
  [["MORE", more], ["TRY", tryit]].forEach(function (km) {
    var a = window[km[0]] && window[km[0]].overlap; if (!a) return; var b = [];
    a.forEach(function (x, i) { b[km[1][i]] = x; }); window[km[0]].overlap = b;
  });
})();
